steps:
  # run immediately
  - label: ":one:"
    command: echo 1
    key: one

  # runs immediately
  - label: ":two:"
    command: echo 2
    key: two

  # waits on one but not two
  - type: waiter
    depends_on:
      - one

  # can be filled out immediately since inputs do not create dependencies
  - input: ":question:"
    fields:
      - text: "First field"
        key: first-field
      - text: "Second field"
        key: second-field

  # runs immediately
  - label: ":three:"
    command: echo 3
    key: three
    depends_on: ~

  # runs after the first waiter
  - label: ":four:"
    command: echo 4
    key: four

  # runs after the first waiter
  - label: ":exclamation:"
    command: buildkite-agent meta-data get first-field --default "NOT SET"
    key: answer

  # runs after answer
  - type: waiter
    depends_on:
      - answer

  # runs after the immediately preceding waiter
  - label: ":five:"
    command: echo 5
    key: five
